---
- name: Jupyter playbook
  hosts: test
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - group_vars/vault_vars.yml
    - group_vars/defaults.yml
  vars:
    ansible_become_pass: "{{ root_pass }}"
    proxy_port: 8888
    root_dir: /opt/jupyter
  tasks:
    - name: ping
      ping: ~

    - name: Create folders
      file: 
        state: directory
        path: "{{ item }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0755
      with_items:
        - "{{ root_dir }}"

    - name: Create a volume
      docker_volume:
        name: "{{ item }}"
      with_items:
        - jupyter

    - name: Jupyter compose.yaml
      template: 
        src: files/jupyter-compose.yaml.j2
        dest: "{{ root_dir }}/jupyter-compose.yaml"
        owner: "{{ user }}"
        group: "{{ group }}" 
        mode: 644
    
    - name: Jupyter create Unit file
      template: 
        src: files/jupyter.service.j2 
        dest: /lib/systemd/system/jupyter.service 
        mode: 644

    - name: Enable Jupyter during boot
      service:
        name: jupyter
        state: started
        enabled: yes
