---
- name: Initial kube node
  hosts: kube
  gather_facts: false
  vars_files:
    - group_vars/vault_vars.yml
  vars:
    ansible_user: root
    ansible_port: 22
    docker_compose_url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64

  tasks:
    - name: ping
      ping: ~

    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 
          'python3-pip', 'virtualenv', 'python3-setuptools','dpkg-dev', 'build-essential',
          'gnupg2', 'git', 'gcc', 'cmake', 'libpcre3', 'libpcre3-dev', 'zlib1g', 'zlib1g-dev',
          'unzip', 'docker.io', 'neofetch' ]

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker Compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: u+x,g+x,o+x

    - name: Enable the required container features
      ansible.builtin.shell: |
        sudo sed -i \
        '$ s/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/' \
        /boot/firmware/cmdline.txt
      args:
        executable: /bin/bash

    - name: br_netfilter
      ansible.builtin.shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        br_netfilter
        EOF
      args:
        executable: /bin/bash

    - name: net.bridge
      ansible.builtin.shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
        sysctl --system
      args:
        executable: /bin/bash

    - name: Change cgroup driver
      ansible.builtin.shell: |
        cat > /etc/docker/daemon.json <<EOF
        { 
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2",
          "experimental" : true
        }
        EOF
      args:
        executable: /bin/bash

    ### Change user
    - name: Update Root user's Password
      user: 
        name: root
        update_password: always 
        password: "{{ root_pass_hash }}"

    - name: Create a login user
      user:
        name: "{{ user }}"
        password: "{{ root_pass_hash }}"
        groups: sudo, docker    # Empty by default. docker, sudo 
        state: present
        shell: /bin/bash        # Defaults to /bin/bash
        system: no              # Defaults to no
        createhome: yes         # Defaults to yes
        home: /home/{{ user }}  # Defaults to /home/<username>

    - name: Authorize key
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_ed25519.pub') }}"

    - name: Configure sshd
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: "^(#)?{{item.key}}"
        line: "{{item.key}} {{item.value}}"
        state: present
      loop:
        - { key: "PermitRootLogin", value: "no" }
        - { key: "PasswordAuthentication", value: "no" } 
        - { key: "Port", value: "2517" }

    - name: Reboot to apply changes
      command: reboot
      async: 1
      poll: 0
      ignore_errors: yes
