---
- name: Test playbook
  hosts: test
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - group_vars/vault_vars.yml
    - group_vars/defaults.yml
  vars:
    ansible_become_pass: "{{ root_pass }}"
    proxy_port: 8888
  tasks:
    - name: ping
      ping: ~

    - name: Create /var/www/{{ domain }}/html folder, set chown USER:USER
      file: 
        state: directory
        path: /var/www/{{ domain }}/html
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700

    - name: Reverse proxy config {{ domain }}.conf
      template:
        src: ./files/https-reverse-proxy.j2
        dest: /etc/nginx/sites-available/{{ domain }}.conf
      notify:
        - reload_nginx  

    - name: Create symbolic link for HTTP version of {{ domain }}.conf to /etc/nginx/sites-enabled
      file:
        state: link
        src: /etc/nginx/sites-available/{{ domain }}.conf
        dest: /etc/nginx/sites-enabled/{{ domain }}.conf
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0700
      notify:
        - reload_nginx

  handlers:
    - name: reload_nginx
      service:
        name: nginx
        state: reloaded
