version: "3.9"
services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: "sonarPassW5%a1"
    volumes:
      - "sonarqube_data:/opt/sonarqube/data"
      - "sonarqube_extensions:/opt/sonarqube/extensions"
      - "sonarqube_logs:/opt/sonarqube/logs"
    ports:
      - "9000:9000"

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_DB: "sonarqube"
      POSTGRES_USER: "sonar"
      POSTGRES_PASSWORD: "sonarPassW5%a1"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ".:/docker-entrypoint-initdb.d" # initialization script
      - "postgresql:/var/lib/postgresql"
      - "postgresql_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
